### ISSUE TITLE
I want to help!

### ISSUE THREAD

**Issue by ZHYPE** [chris-gong/fortnite-clone-ue4#12]
Would you be interested in creating software together with me and a few of my friends. We are only in 8th grade but were interested in game programming, ai, and we also enjoy creating product ideas with the intent to sell them at a future time. 

p.s. i realize this is not an issue :)

**Comment by chris-gong** [comment]
Hi @ZHYPE, I appreciate your offer, but I am currently busy at the moment. However, please visit our discord if you wish to help us with this game: https://discord.gg/2xbR5qT
