### ISSUE TITLE
Build error on vs2019 

### ISSUE THREAD

**Issue by 0xsmft** [chris-gong/fortnite-clone-ue4#15]
Heres a pic 
![Why](https://user-images.githubusercontent.com/49040508/57219528-490e0300-6ff0-11e9-8039-d68ab68d61b0.png)

**Comment by 0xsmft** [comment]
oh I get this as well 
![Why2](https://user-images.githubusercontent.com/49040508/57219895-64c5d900-6ff1-11e9-98c9-63cd028221fe.png)
![why3](https://user-images.githubusercontent.com/49040508/57219896-64c5d900-6ff1-11e9-81e0-6800c47beed1.png)

**Comment by chris-gong** [comment]
Hi @BEASTSM96, it's because you're missing dll and lib files required for the gameliftclient sdk. Please refer to step 2 in the readme and let me know how it goes.

**Comment by BEASTSM96** [comment]
ok ill will do that

**Comment by 0xsmft** [comment]
i've go it  you needed  to add to aswcore to ue4_22
