### ISSUE TITLE
Client-side prediction

### ISSUE THREAD

**Issue by chris-gong** [chris-gong/fortnite-clone-ue4#16]
Specifically for mechanics like building and shooting. To compensate for server lag aka the delay between when the clients presses a button and the server processing the request to spawn an actor, I will eventually try to spawn the actor on the client first and remove it later in hopes that the actor has spawned on the server by then.

**Comment by chris-gong** [comment]
Client side prediction for building was implemented by first building on the client, assigning that structure an id ,adding this structure with the assigned id to an array, then calling a server rpc to spawn that exact same structure. From that rpc, a client rpc would be called to destroy that structure with that specific id by searching through an array that is only on the client side. This was implemented in 0af9b3958bc89407fcf20ed4c4ceebec8d910e37. 

Not the most efficient. A better solution, albeit it would require more space, would be to spawn all the structures ahead of time, but make them invisible.

**Comment by Moshiach770** [comment]
Chris, you're not only a genius, but a kind soul sharing this awesome knowledge with the rest of us.
