### ISSUE TITLE
Lobby UI with unique umap assigned to it

### ISSUE THREAD

**Issue by pivotman319-owo** [chris-gong/fortnite-clone-ue4#23]
Add in a simple user interface similar to Battle Royale/Save the World's lobby, complete with a custom umap file assigned to it.

**Comment by chris-gong** [comment]
Thank you for the suggestion. We will definitely try to implement this!

**Comment by chris-gong** [comment]
Going to close this since you've opened a new issue that is very similar. Further discussion will just be moved to the other issue.
