### ISSUE TITLE
No UI Telling that the storm is moving 

### ISSUE THREAD

**Issue by 0xsmft** [chris-gong/fortnite-clone-ue4#34]
It's hard to know if the storm is moving or not 

Until your at the edge of it

**Comment by chris-gong** [comment]
Yes I agree, this is definitely something we plan to implement.

**Comment by BEASTSM96** [comment]
Yep just I cant actually do this lol

**Comment by BEASTSM96** [comment]
help-wanted

**Comment by 0xsmft** [comment]
Added enhancement
