### ISSUE TITLE
Traps? 

### ISSUE THREAD

**Issue by 0xsmft** [chris-gong/fortnite-clone-ue4#36]
In Fortnite they have the spike traps I think we need this in FNClone

**Comment by 0xsmft** [comment]
*error wasn't supposed to be closed*

**Comment by pivotman319-owo** [comment]
We could do that, but atm we have not yet advanced Weekly to a point where the building system supports editing.

(that, and Epic apparently vaulted spike traps somewhere in between v11.50/12.00)

**Comment by 0xsmft** [comment]
Yes Epic did vault the traps and yes the building system needs to be more advanced
