### ISSUE TITLE
Chopping materials in dedicated server spawns a black ball

### ISSUE THREAD

**Issue by SalahAdDin** [chris-gong/fortnite-clone-ue4#42]
Hi guys, i'm testing this project.

I played as a dedicated server and i found this bug:
![imagen](https://user-images.githubusercontent.com/5034215/81750607-85ebc000-94b6-11ea-9fdf-093b778bcf0a.png)

Do you know what happens here?

**Comment by 0xsmft** [comment]
does the ball move? or just stays

**Comment by SalahAdDin** [comment]
The ball just stays in its position(if the player turns around the position do it with it).

**Comment by SalahAdDin** [comment]
@chris-gong Did you fix it?

**Comment by chris-gong** [comment]
I'm currently in the process of remaking the feature so not yet.
