### ISSUE TITLE
Please make compatible for 4.21

### ISSUE THREAD

**Issue by yasser-noori** [chris-gong/fortnite-clone-ue4#5]

**Comment by chris-gong** [comment]
Hi Anar, thanks for checking in. I will definitely look into this and make it compatible soon.

**Comment by chris-gong** [comment]
@AnarAwards I am currently using Unreal 4.21, what is the specific issue you're running into?

**Comment by yasser-noori** [comment]
@chris-gong 

Hello Chris,

I’m currently using Unreal Engine 4.21.1

When I download your project from Github and than open it, it tells me that the following modules (“FortniteClone”) are built with a different version of unreal engine. Than it rebuilds it.

Build Log:
 Running C:/Program Files/Epic Games/UE_4.21/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="C:/Users/Noori/Documents/Unreal Projects/fortnite-clone-ue4-master/qbc.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Performing full C++ include scan (building a new target)
Creating makefile for FortniteCloneEditor (no existing makefile)
Using Visual Studio 2017 14.15.26726 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).

Than it tells me that the build fails and tells me to compile from source manually which I don’t know how to because i’m fairly new to Unreal Engine. Can you please guide me on how to open this project? Thank you!

**Comment by AnarAwards** [comment]
Please Reply.

**Comment by yasser-noori** [comment]
Please reply.

**Comment by chris-gong** [comment]
@AnarAwards I just got back in school so I've been busy lately. I'll try to recreate the issue tonight.

**Comment by yasser-noori** [comment]
I think the issue is that it requires Visual Studios 2015, and i'm currently using visual studios 2017. I know your a busy student, but since your done the first release, could you please upgrade it to visual studios 2017? I’m really interested in this project because its is very unique. Thank you!

**Comment by chris-gong** [comment]
Hi @yassernoori my apologies. I'm currently trying to troubleshoot this now. I am also using Visual Studio 2017. I will update this thread very soon with how I normally run this project after I download the repository.

**Comment by yasser-noori** [comment]
Have you fixed the issue yet?

**Comment by chris-gong** [comment]
Hi @yassernoori it seems that there's an issue with the plugins. Trying to fix this so that people don't have to manually add the plugins themselves.

**Comment by chris-gong** [comment]
Hi @yassernoori I'm sorry for the long wait, but please try the following the instructions in the README from this commit 92ecd810f40bde215dbbf046e309d456db6fd8cd and let me know if you're able to run the game.

**Comment by chris-gong** [comment]
I've confirmed with other people that the instructions in the readme work, so if you're still having issues related to building and running, then ask on my discord: https://discord.gg/2xbR5qT
