### ISSUE TITLE
game sessions

### ISSUE THREAD

**Issue by aleks365** [chris-gong/fortnite-clone-ue4#7]
I will be able to create my game sessions because I would like to play with a friend?

**Comment by chris-gong** [comment]
@aleks365 Hi Aleks, currently we do not have the ability for the users to make sessions. However, follow the latest release as we will be posting game session codes later today!

**Comment by aleks365** [comment]
I can not wait ;)

**Comment by aleks365** [comment]
I noticed such a mistake that the mouse does not react to movement in the game, unless I keep the right mouse button

**Comment by chris-gong** [comment]
@aleks365 hey, I noticed this as well. We're going to do another test maybe later tonight. Just wondering, do you get notifications when we make new releases? Also, thank you so much for the feedback, if you want to talk further about the game, here is our discord: https://discord.gg/2xbR5qT

**Comment by aleks365** [comment]
I am waiting for next tests. He gets notifications by email. I do not know English very well, I will not help much, but I will try ;)

**Comment by chris-gong** [comment]
In this release https://github.com/chris-gong/fortnite-clone-ue4/releases/tag/v1.6.1, we have added the ability for users to create/join game sessions without inputting a code. This feature was implemented by modifying the gamelift client sdk and adding a queue to Gamelift on which game sessions are made off of.
